### ISSUE TITLE
Question about World Map Waystone syncing.

### ISSUE THREAD

**Issue by Gamemassa** [rfresh2/XaeroPlus#135]
Minecraft 1.20.4
Fabric 0.15.11
Fabric API 0.97.0
Waystones 16.0.3
Xaero's WorldMap 1.38.4
Xaero Plus 2.11 (Fabric) (WM1.38.4 MM24.1.1)

Hi, I'm just wondering why, when waypoints are added to Xaero's World Map for Waystones, they're added as temporary waypoints. And more specifically, why does it seem like when I try to switch them to permanent ones, and then close and reopen World Map, suddenly there are duplicate waypoints for all the waystones?

**Comment by rfresh2** [comment]
They are added as temporary waypoints to allow a full resync every time you connect to a MC server

So this means we get the following advantages:
1. any issues during the sync can be resolved by a reconnect
2. waystones that get deleted don't stay as waypoints forever
3. waystone name changes always get updated into the waypoints
4. you can disable the waystone sync or remove XP and your waypoint list gets cleaned up automatically

but if you try to make those temp waypoints into permanent ones, XP has no context about them being waystones and it will never delete permanent waypoints. so that's why you get duplicates.

**Comment by Gamemassa** [comment]
> They are added as temporary waypoints to allow a full resync every time you connect to a MC server
> 
> So this means we get the following advantages:
> 
> 1. any issues during the sync can be resolved by a reconnect
> 2. waystones that get deleted don't stay as waypoints forever
> 3. waystone name changes always get updated into the waypoints
> 4. you can disable the waystone sync or remove XP and your waypoint list gets cleaned up automatically
> 
> but if you try to make those temp waypoints into permanent ones, XP has no context about them being waystones and it will never delete permanent waypoints. so that's why you get duplicates.

So, if I'm understanding this correctly, I should leave the waystone waypoints as temporary ones, because if they're set to permanent XP doesn't see them? (Side question, do Temporary waypoints not go away over time? For some reason I thought they did, which is why I was making my waystone waypoints permanent.)

**Comment by rfresh2** [comment]
Yeah just don't make them into permanent waypoints and everything will work correct

> do Temporary waypoints not go away over time

Yes. that's how XP can do a full waystone waypoint resync constantly. Existing temp waypoints get deleted, XP adds fresh new temp waypoints

**Comment by Gamemassa** [comment]
Oh, gotcha! Thanks for the explanation!

**Comment by Gamemassa** [comment]
@rfresh2 Almost forgot to ask, am I still able to change the color of the waypoints?

**Comment by rfresh2** [comment]
No. But there's an XP setting to change how waystone colors are selected. Your only choices are either a consistent random function based on the waystone name (default) or all the same color of your choice.
