### ISSUE TITLE
[Feature Request] Save map and waypoint content on load, rather than on world save.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [rfresh2/XaeroPlus#142]
I have a problem with my PC which causes it to crash regularly - https://github.com/PrismLauncher/PrismLauncher/issues/2139#issuecomment-2025439526 - and when it crashes whilst playing on my brother's LAN-hosted world, when I rejoin, all of my waypoints (and usually some of my map content) is deleted. Consequently, it should save the content *when it changes* rather than when the user disconnects. Hopefully this could be implemented in this, especially if https://github.com/rfresh2/XaeroPlus/issues/125#issue-2172404231 is accepted.

**Comment by rfresh2** [comment]
waypoints are already saved immediately on add or edit operations.

map data is saved async constantly because otherwise it would cause large fps spikes while it's writing to your hard drive. 

the map data files themselves are megabytes in size and compressed, saves immediately on the render thread would have pretty significant performance impact

so it is still saved on changes, and its usually pretty quick after changes. just not immediately like when the chunks finish being loaded

**Comment by RokeJulianLockhart** [comment]
> https://github.com/rfresh2/XaeroPlus/issues/142#issuecomment-2184156825

@rfresh2, indeed. I and my brother have had to switch to https://www.curseforge.com/minecraft/mc-mods/journeymap/files/5208387 instead of Xaero because it would randomly delete map data for both of us, so I probably erroneously attributed it to the issue I was having. Glad to hear that it's designed well in the regard I wanted, though.
