### ISSUE TITLE
Is there a way always render players regardless of where in the world they are

### ISSUE THREAD

**Issue by Plasman888** [rfresh2/XaeroPlus#162]
There should be a way but I cant seem to find it

**Comment by rfresh2** [comment]
there's a player location sharing feature in the base worldmap/minimap mods. i think it requires you to install them on the server as well. There's a button on the bottom right side of the WorldMap gui.

XaeroPlus doesn't add or change any features related to this so that's as much support as i can give.

**Comment by Plasman888** [comment]
Ngl I have no clue how to use the button but welp I'll just comment thus on the Xaeros mod page
