### ISSUE TITLE
1.12.2 MM24.5.0 crash

### ISSUE THREAD

**Issue by al-wei** [rfresh2/XaeroPlus#171]
XaeroPlus-Forge-1.12.2-166-WM1.39.0-MM24.5.0
MM24.5.0
https://mclo.gs/fFfWHaa

**Comment by Mike74846** [comment]
I have test only with this mods and it work fine. It must a other mods of your list a problem have.

Tested with this mod:

- Xaero`s Minimap Mod Version: 24.5.0
- Xaero`s Worldmap Version: 1.39.0
- Xaeroplus Mod Version: 166
- !MixinBooter Mod Version 9.4

I hope he find the Mod what the Problem make but XaeroPlus or a other of this 3 Mods make not the Problem

**Comment by rfresh2** [comment]
I cannot troubleshoot 405 mods

you will need to find which mod in particular is conflicting by using binary search

```
A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.

Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.

Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods out of order.

By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.
```

**Comment by rfresh2** [comment]
[XaeroPlus-1.12.2-testfix-DEV1.zip](https://github.com/user-attachments/files/17263424/XaeroPlus-1.12.2-testfix-DEV1.zip)

You can test if this fixes it but without knowing the conflicting mod i can't test for myself

**Comment by Mike74846** [comment]
I looked a little in the crash report and that's what the lines at the top said.

This 2 areas say a Problem with the XaeroPlus Mod. I have no idear help this for you?

27  | Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.xaeroplus.json:mc.MixinNetworkManager from mod XaeroPlus-Forge-1.12.2-166-WM1.39.0-MM24.5.0.jar] from phase [DEFAULT] in config [mixins.xaeroplus.json] FAILED during PREPARE
--
28 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:667)
29 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:613)
30 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:557)
31 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:476)
32 | ... 17 more
33 | Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.xaeroplus.json:mc.MixinNetworkManager from mod XaeroPlus-Forge-1.12.2-166-WM1.39.0-MM24.5.0.jar target net.minecraft.network.NetworkManager was loaded too early.

**Comment by rfresh2** [comment]
I already saw and no that is not enough info to find the conflicting mod

**Comment by al-wei** [comment]
> I already saw and no that is not enough info to find the conflicting mod

!mixinbooter-9.4
OptiFine_1.12.2_HD_U_G5_MOD
XaeroPlus-Forge-1.12.2-166-WM1.39.0-MM24.5.0
Xaeros_Minimap_24.5.0_Forge_1.12
XaerosWorldMap_1.39.0_Forge_1.12

https://mclo.gs/rM1Mx5U

**Comment by al-wei** [comment]
> > I already saw and no that is not enough info to find the conflicting mod
> 
> !mixinbooter-9.4 OptiFine_1.12.2_HD_U_G5_MOD XaeroPlus-Forge-1.12.2-166-WM1.39.0-MM24.5.0 Xaeros_Minimap_24.5.0_Forge_1.12 XaerosWorldMap_1.39.0_Forge_1.12
> 
> https://mclo.gs/rM1Mx5U

OptiFine
Very amazing

**Comment by rfresh2** [comment]
Gotcha thanks was able to reproduce now

and the build i posted before fixes it for me so i will push that as a release

**Comment by rfresh2** [comment]
published now https://github.com/rfresh2/XaeroPlus/releases/tag/Forge-1.12.2-167

and on modrinth/curseforge whenever they approve
