### ISSUE TITLE
Java crashes again when loading the world on macOS

### ISSUE THREAD

**Issue by Wionsito** [rfresh2/XaeroPlus#55]
This bug was already fixed by Xaero on update 1.33.1
![Update Log Screenshot](https://github.com/rfresh2/XaeroPlus/assets/82771944/4908cbb9-208c-48b0-a693-e153575ec629)

But when using XaeroPlus the bug is reintroduced, I'm using the latest versions of XaeroPlus, Xaeros Minimap and Xaeros Worldmap.

When I disable XaeroPlus the game doesn't crash.

**Comment by rfresh2** [comment]
Please attach the latest.log during the crash

**Comment by Wionsito** [comment]
> Please attach the latest.log during the crash

[latest.log](https://github.com/rfresh2/XaeroPlus/files/12571050/latest.log)

**Comment by rfresh2** [comment]
I'm not seeing any indication of a crash in that log file. Is it possible you could replicate it on an instance with only xaeroplus, worldmap, and minimap installed?

The xaero changelog you've linked says he fixed a crash but I'm not sure exactly what he did to do so. I overwrite large parts of his codebase so I need to find what is the root cause of it. So any logs that are relevant would be helpful

**Comment by Wionsito** [comment]
Bug is fixed now

**Comment by ghost** [comment]
For the record, I see you're using an Apple Silicon Mac. This is probably #68 (not fixed for me but there is a workaround).
