### ISSUE TITLE
Game randomly crashes with aarch64 assembly error

### ISSUE THREAD

**Issue by ghost** [rfresh2/XaeroPlus#68]
This is the bug I reported previously on Discord, just making a formal bug report now.

It's pretty random when this happens, but I keep getting this on my M1 Mac with Fabric/Quilt 1.20.1/1.20.2.

**Workaround**: Run Minecraft in Rosetta using an x86_64 Java installation (may incur a slight performance penalty).

* https://mclo.gs/juASULk
* https://mclo.gs/mKF08c8
* https://mclo.gs/H2h0NvA

**Comment by rfresh2** [comment]
Could be a bug in mixin or in the aarch64 jdk itself

i'm not doing anything particularly weird that would be CPU architecture specific in XaeroPlus so i have no clue

**Comment by ghost** [comment]
Might be related: https://bugs.openjdk.org/browse/JDK-8310844

**Comment by PoTheMagicDragon** [comment]
I ran into this same issue on prism launcher and it only happened to me after a world had been loaded for a bit (less than a minute, more than a few seconds). I tried opening a world several times, and then didn't press any keys and it seemed like it crashed at a fairly consistent interval. I wonder if it's tied to an intermittent task like saving the world or something similar. 

I was able to use 0xallie's workaround and run prism launcher in rosetta and & using an x86_64 java version. 

I might come back to this later and see if I can narrow things down at all. If you want any help debugging or trying things out, dm me on discord @pothemagicdragon

Note to future self for things to try:
- Run in different launchers
- Run on forge instead of fabric
- Find exact times for how long the world is loaded before it crashes
- Look more into the logs to see if there are any consistent events that happen right before the crash

**Comment by rfresh2** [comment]
I've gotten some early reports of success with this commit: https://github.com/rfresh2/XaeroPlus/commit/e3d5658a4230444dceae8b47b93c9474c9217de8

I'm looking for people to test it over a few hours of playtime and confirm it does or does not fix

[Prebuilt Fabric 1.20.1 jar](https://github.com/rfresh2/XaeroPlus/files/13836156/xaeroplus-armjavafix-e3d565.zip)

**Comment by DeliveryAagent** [comment]
> Hey, same issue here, m2 mac.
> 
> Pretty much the same behaviour than other people.
> I've tried @rfresh2's build and still get the same crashes (after few seconds).

Forget about that, seems to be working right now, will keep testing it

**Comment by rfresh2** [comment]
> Hey, same issue here, m2 mac.
> 
> Pretty much the same behaviour than other people. I've tried @rfresh2's build and still get the same crashes (after few seconds).

Could you send the crash log to me either here (paste into https://mclo.gs/) or on discord DM's? 

I want to figure out if its changed at all

**Comment by DeliveryAagent** [comment]
I pinged you on Discord @rfresh2

**Comment by rfresh2** [comment]
I've received a couple reports that its working so I pushed the update

if anyone still has issues you can reply here or dm me directly
