### ISSUE TITLE
Add a disclaimer on your mod pages

### ISSUE THREAD

**Issue by thexaero** [rfresh2/XaeroPlus#89]
Add a disclaimer on your mod pages that your mod removes limitations in my mods that are there for a reason and will cause critical bugs and crashes. I am very tired of having to waste my time trying to figure out if every reported unreproducible bug is caused by your mod or not. 
Thanks in advance!

**Comment by rfresh2** [comment]
> Add a disclaimer on your mod pages that your mod removes limitations in my mods that are there for a reason and will cause critical bugs and crashes

With all due respect, I don't agree that limitations being changed in XP necessarily causes bugs and crashes. Otherwise I don't think many people would find XP useful.

Nor do i believe a disclaimer will change user reporting behavior. _Most users don't read the README_

There's over [40 lines of text already dedicated](https://github.com/rfresh2/XaeroPlus/blob/fabric-1.20.1/README.md?plain=1#L61-L101) to describing the nature of these changes being extensive and invasive. 

> I am very tired of having to waste my time trying to figure out if every reported unreproducible bug is caused by your mod or not

I do empathize with you, it would be aggravating for both yourself and users if you can't trust reported exceptions or are unable to reproduce issues.

With regard to issue reports, if a user is using XP you can always forward them here or my discord server. 

But if you actually want to solve this problem long term, **you should consider collaborating with me instead of requesting disclaimers.**

I have more experience in your codebase than anyone except you. Let's work together to (1) _prevent users from having issues in the first place_, and (2) _make it clear who to report it to when they do_.

w.r.t (1) I think there are ways to decrease complexity on both our ends. I often must do convoluted hacks or overwrites for what would be far simpler and maintainable in your source code. More importantly, I think the end product could be better if we worked together on certain features or problems.

and w.r.t (2) We can find code paths where XP should create clearly distinct log statements or exceptions rather than existing ones. I think this will reduce the time required on your part investigating reported issues.

Please reach out to me directly on discord: `rfresh` to discuss if you'd be open to this

**Comment by thexaero** [comment]
I asked you to add a disclaimer on your mod pages, not your README, and it would be there for modpack creators to know not to add your mod to their packs because it is, at this moment, guaranteed to cause issues. It seems like every time I receive a weird bug report that makes absolutely no sense and spend hours thinking about it, the reporting user always has your mod installed. 
> I don't agree that limitations being changed in XP necessarily causes bugs and crashes. 

This statement showcases your attitude towards what you're doing. A lot of limitations are not there for performance reasons, they're often there because some code somewhere doesn't work right without them and needs to be rewritten and tested before limits are removed. The bugs/crashes wouldn't even look related to your addon. For example, if you were to simply increase the number of branch levels to something higher than 3, all hell would break loose, and you wouldn't care because you have no idea about any niche bugs, as they're not reported to you. Level 4 is where a single branch texture can contain more than 1 leaf region, which is unlikely to work atm. Most of the code related to that looks like it expects it, but I haven't actually tested any of it. All limitations have something like that. There are many places in the code which nobody should touch under any circumstances. I don't want to trust a random addon to do it safely. 
And I am currently not enjoying this issue #68 being reintroduced into my mod by your addon and everyone blaming me. I had to waste a whole day trying to make sure it wasn't happening with just my mods. I know this one isn't directly about removing limitations, but that's mostly why people use your addon. I am fairly certain your dimension switching feature was causing all sorts of reported unexplainable visual glitches on the map too. That was likely the biggest contributor to issues caused by your mod in general, which is why I had to address it first.

**Comment by rfresh2** [comment]
> And I am currently not enjoying this issue #68 being reintroduced into my mod by your addon and everyone blaming me. I had to waste a whole day trying to make sure it wasn't happening with just my mods

This is a good example of where better communication between us could resolve issues very quickly. You seem to have an idea of the cause and fix, so I'm all ears. 

Anyway, here's my proposal:

1. I add a statement to the top of the README (also referring to the mod pages):

```
XaeroPlus is not affiliated or endorsed by xaero96.

If you use XaeroPlus, please direct ALL support issues, including those relating to Xaero's WorldMap and Minimap, to XaeroPlus issues (link) or Discord (link)
```

2. Any exceptions emitted that link to your support page (i.e. the links appended in `CrashHandler` and `MinimapInterface`) I instead link to this issue tracker and include XaeroPlus in the exception description. 

I'm not going to advertise that XP is actively causing bugs and crashes when you have yet to clearly identify them. If they are identified, I'm willing and able to resolve them whether it requires more changes or removing the changes entirely. 

If what you say about XP is true, that it is "guaranteed to cause issues", modpack owners and users can try it and decide for themselves whether to use XP or not. But I don't think it is true based on my own playtesting and talking to users and modpack owners. 

I'm going to keep pushing features that myself and my users want. Will that sometimes result in bugs? Just like any software, including your own, absolutely. I can't stop users from going to you for help, but I can do my best to direct them away from you and resolve issues if I'm made aware of them.

**Comment by odpay** [comment]
@thexaero to avoid unwanted bug reports on your end, i advise making it clear to your users that if they are using XP or any other mods that mixin with xaero. that they should attempt to recreate without said mods, and if the issue doesn't persist, then to report the bug to the respective addition mod's authors.

**Comment by thexaero** [comment]
@odpay I would love for this to be that simple. The bugs are usually very difficult to reproduce and the users reporting them have no idea what causes them. And I don't want to have to redirect people after wasting my time investigating every issue. That's the problem with mods like XaeroPlus that do way too much.

**Comment by thexaero** [comment]
@rfresh2 I know your proposal solves the issue in your mind, but it wouldn't change anything for me. People don't normally follow the link in the crash report, they go to my page manually. 
Your first and only concern right now needs to be removing huge chunks of my code from your code released as open source without my permission.

**Comment by Avanatiker** [comment]
@thexaero maybe start making xaero minimap gud (or open source) and people dont have to try to fix your mess.

**Comment by rfresh2** [comment]
locking this before it goes further off the rails lol
